//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication_Vigor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeComponent
    {
        public int ID { get; set; }
        public int RecipeId { get; set; }
        public string Component { get; set; }
        public string Measurement { get; set; }
        public int Quantity { get; set; }
        public string Calories { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
